name: "Terraform Plan"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  changed-envs:
    name: Detect Changed Terraform Environments
    runs-on: ubuntu-latest
    outputs:
      changed-envs: ${{ steps.set-changed-envs.outputs.changed-envs }}
    permissions:
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Filter Path
        id: filter
        uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        with:
          filters: |
            Stage: 
              - 'stage/**.tf'
              - 'modules/**.tf'
            Prod:
              - 'prod/**.tf'
              - 'modules/**.tf'

      - name: Set Changed Environments
        id: set-changed-envs
        run: |
          # detect changed terraform environment definitions in pull request
          if [ ${{ github.event_name }} = 'pull_request' ]; then
            echo 'changed-envs=${{ steps.filter.outputs.changes }}' >> $GITHUB_OUTPUT
          
          # if workflow was started manually, use all terraform environments
          else
            echo 'changed-envs=["Stage","Prod"]' >> $GITHUB_OUTPUT
          
          fi

      - name: print
        run: echo '${{ steps.set-changed-envs.outputs.changed-envs }}'


  terraform-plan:
    needs: changed-envs
    name: Plan for ${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: ${{ fromJSON(needs.changed-envs.outputs.changed-envs) }}
    permissions:
      pull-requests: write
    steps:
      - name: Set Uppercase Name for Environment
        id: env-upper
        run: echo "ENV_UPPER=$(echo ${{ matrix.env }} | tr [:lower:] [:upper:])" >> $GITHUB_ENV
      
      - name: Set Lowercase Name for Environment
        id: env-lower
        run: echo "ENV_LOWER=$(echo ${{ matrix.env }} | tr [:upper:] [:lower:])" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        if: github.event_name == 'workflow_dispatch'
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}
      
      # Generate Infracost JSON file if workflow started manually
      - name: Generate Infracost cost estimate
        id: cost
        if: github.event_name == 'workflow_dispatch'
        run: |
          infracost breakdown --path=. \
                              --format=json \
                              --out-file=/tmp/infracost.json \
                              --terraform-var="project=${{ vars[format('GCP_PROJECT_ID_{0}', env.ENV_UPPER)] }}"
        working-directory: ./${{ env.ENV_LOWER }}
        continue-on-error: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Authenticate
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -diff -recursive -no-color . ../modules
        working-directory: ./${{ env.ENV_LOWER }}
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"
        working-directory: ./${{ env.ENV_LOWER }}
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./${{ env.ENV_LOWER }}
        continue-on-error: true

      - name: Terraform Plan
        id: plan
        if: steps.validate.outcome == 'success'
        run: terraform plan -var="project=${{ vars[format('GCP_PROJECT_ID_{0}', env.ENV_UPPER)] }}" -no-color -input=false
        working-directory: ./${{ env.ENV_LOWER }}
        continue-on-error: true
      
      - name: Terraform Summary
        run: |
          # Terraform Summary for Format, Init, Validation and the Plan

          echo -e "::group::Format and Style: ${{ steps.fmt.outcome == 'success' && '\033[32;1m' || '\033[31m' }}${{ steps.fmt.outcome }}\033[0m"
          echo -e "${{ steps.fmt.outputs.stderr }}"
          echo -e "${{ steps.fmt.outputs.stdout }}"
          echo "::endgroup::"

          echo -e "::group::Initialization: ${{ steps.init.outcome == 'success' && '\033[32;1m' || '\033[31m' }}${{ steps.init.outcome }}\033[0m"
          echo -e "${{ steps.init.outputs.stderr }}"
          echo -e "${{ steps.init.outputs.stdout }}"
          echo "::endgroup::"

          echo -e "::group::Validation: ${{ steps.validate.outcome == 'success' && '\033[32;1m' || '\033[31m' }}${{ steps.validate.outcome }}\033[0m"
          echo -e "${{ steps.validate.outputs.stderr }}"
          echo -e "${{ steps.validate.outputs.stdout }}"
          echo "::endgroup::"

          echo -e "::group::Plan: ${{ steps.plan.outcome == 'success' && '\033[32;1m' || '\033[31m' }}${{ steps.plan.outcome }}\033[0m"
          echo -e "${{ steps.plan.outputs.stderr }}"
          echo -e "${{ steps.plan.outputs.stdout }}"
          echo "::endgroup::"

          echo "::group::Cost Breakdown:"
          infracost output --path=/tmp/infracost.json \
                           --format=table \
                           --show-skipped
          echo "::endgroup::"
      
      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          FORMAT: ${{ steps.fmt.outputs.stdout }}
          INIT: ${{ steps.init.outputs.stdout }}
          VALIDATE: ${{ steps.validate.outputs.stdout }}
          PLAN: ${{ steps.plan.outputs.stdout }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const format_output = `
            <details><summary>Show Format and Style Errors</summary>
            \`\`\`diff\n
            ${process.env.FORMAT} 
            \`\`\`
            </details>`;

            const init_output = `
            <details><summary>Show Output</summary>
            \`\`\`diff\n
            ${process.env.INIT} 
            \`\`\`
            </details>`;

            const validate_output = `
            <details><summary>Show Validation Errors</summary>
            \`\`\`diff\n
            ${process.env.VALIDATE} 
            \`\`\`
            </details>`;

            const plan_output = `
            <details><summary>Show Plan</summary>
            \`\`\`diff\n
            ${process.env.PLAN} 
            \`\`\`
            </details>`;

            const output = `## 🏞 ${{ matrix.env }} - Terraform Config
            ### 🖌 Format and Style: \`${{ steps.fmt.outcome }}\`
            ${{ steps.fmt.outcome == 'failure' && '${format_output}' || '' }}
            ### 🛠 Initialization: \`${{ steps.init.outcome }}\`
            ${{ steps.init.outcome == 'failure' && '${init_output}' || '' }}
            ### 🔎 Validation: \`${{ steps.validate.outcome }}\`
            ${{ steps.validate.outcome == 'failure' && '${validate_output}' || '' }}
            ### 📖 Plan: \`${{ steps.plan.outcome }}\`
            ${{ steps.validate.outcome != 'skipped' && '${plan_output}' || '' }};

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

  infracost:
    needs: changed-envs
    name: Infrastructure Cost Breakdown for PR
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    permissions:
      pull-requests: write
    steps:
      - name: Setup Infracost
        uses: infracost/actions/setup@v2
        with:
          api-key: ${{ secrets.INFRACOST_API_KEY }}

      - name: Checkout Base Branch
        uses: actions/checkout@v3
        with:
          ref: '${{ github.event.pull_request.base.ref }}'

      # Generate Infracost JSON file as the baseline.
      - name: Generate Stage Infracost cost estimate baseline
        if: contains(fromJSON(needs.changed-envs.outputs.changed-envs), 'Stage')
        run: |
          infracost breakdown --path=stage \
                              --format=json \
                              --out-file=/tmp/infracost-base-stage.json \
                              --terraform-var="project=${{ vars.GCP_PROJECT_ID_STAGE }}"
      
      - name: Generate Prod Infracost cost estimate baseline
        if: contains(fromJSON(needs.changed-envs.outputs.changed-envs), 'Prod')
        run: |
          infracost breakdown --path=prod \
                              --format=json \
                              --out-file=/tmp/infracost-base-prod.json \
                              --terraform-var="project=${{ vars.GCP_PROJECT_ID_PROD }}"

      - name: Checkout PR Branch
        uses: actions/checkout@v3

      # Generate an Infracost diff and save it to a JSON file.
      - name: Generate Stage Infracost diff
        if: contains(fromJSON(needs.changed-envs.outputs.changed-envs), 'Stage')
        run: |
          infracost diff --path=stage \
                        --format=json \
                        --compare-to=/tmp/infracost-base-stage.json \
                        --out-file=/tmp/infracost-diff-stage.json \
                        --terraform-var="project=${{ vars.GCP_PROJECT_ID_STAGE }}"
      
      - name: Generate Prod Infracost diff
        if: contains(fromJSON(needs.changed-envs.outputs.changed-envs), 'Prod')
        run: |
          infracost diff --path=prod \
                        --format=json \
                        --compare-to=/tmp/infracost-base-prod.json \
                        --out-file=/tmp/infracost-diff-prod.json \
                        --terraform-var="project=${{ vars.GCP_PROJECT_ID_PROD }}"
      
      - name: Post Infracost comment to PR
        run: |
            infracost comment github --path="/tmp/infracost-diff-*.json" \
                                    --show-skipped \
                                    --show-all-projects \
                                    --repo=$GITHUB_REPOSITORY \
                                    --github-token=${{github.token}} \
                                    --pull-request=${{github.event.pull_request.number}} \
                                    --behavior=new
