name: "Terraform Plan"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - '**.tf'

jobs:
  changed-envs:
    name: Detect Changed Terraform Environments
    runs-on: ubuntu-latest
    outputs:
      changed-envs: ${{ steps.set-changed-envs.outputs.changed-envs }}
    permissions:
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Filter Path
        id: filter
        uses: dorny/paths-filter@v2
        if: github.event_name == 'pull_request'
        with:
          filters: |
            Stage: 
              - 'stage/**.tf'
              - 'modules/**.tf'
            Prod:
              - 'prod/**.tf'
              - 'modules/**.tf'

      - name: Set Changed Environments
        id: set-changed-envs
        run: |
          # detect changed terraform environment definitions in pull request
          if [ ${{ github.event_name }} = 'pull_request' ]; then
            echo "changed-envs=${{ steps.filter.outputs.changes }}" >> $GITHUB_OUTPUT
          
          # if workflow was started manually, use all terraform environments
          else
            echo "changed-envs=['Stage','Prod']" >> $GITHUB_OUTPUT
          
          fi

  terraform-plan:
    needs: changed-envs
    name: Plan for ${{ matrix.env }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: ${{ fromJSON(needs.changed-envs.outputs.changed-envs) }}
    permissions:
      pull-requests: write
    steps:
      - name: Set Uppercase Name for Environment
        id: env-upper
        run: echo "ENV_UPPER=$(echo ${{ matrix.env }} | tr [:lower:] [:upper:])" >> $GITHUB_ENV
      
      - name: Set Lowercase Name for Environment
        id: env-lower
        run: echo "ENV_LOWER=$(echo ${{ matrix.env }} | tr [:upper:] [:lower:])" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Authenticate
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.SERVICE_ACCOUNT_KEY }}'

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check -diff -recursive -no-color . ../modules
        working-directory: ./${{ env.ENV_LOWER }}
        continue-on-error: true
      
      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ vars.TF_STATE_BUCKET }}"
        working-directory: ./${{ env.ENV_LOWER }}
      
      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ./${{ env.ENV_LOWER }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -var="project=${{ vars[format('GCP_PROJECT_ID_{0}', env.ENV_UPPER)] }}" -no-color -input=false
        working-directory: ./${{ env.ENV_LOWER }}
        continue-on-error: true

      - name: Update Pull Request
        uses: actions/github-script@v6
        if: github.event_name == 'pull_request'
        env:
          PLAN: ${{ steps.plan.outputs.stdout }}
          FORMAT: ${{ steps.fmt.outputs.stdout }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const format_output = `
            <details><summary>Show Format and Style Errors</summary>

            \`\`\`diff\n
            ${process.env.FORMAT}
            \`\`\`

            </details>`;

            const output = `### Terraform ${{ matrix.env }} Config
            #### 🖌 Format and Style: \`${{ steps.fmt.outcome }}\`
            ${{ steps.fmt.outcome == 'failure' && '${format_output}' }}

            #### 🛠 Initialization: \`${{ steps.init.outcome }}\`
            
            #### 🔎 Validation: \`${{ steps.validate.outcome }}\`
            #### 📖 Plan: \`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`terraform\n
            ${process.env.PLAN}
            \`\`\`

            </details>`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      # - name: Terraform Apply
      #  if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #  run: terraform apply -auto-approve -var="project=${{ vars.GCP_PROJECT_ID }}" -input=false